name: Trigger Lambda

on:
  push:
    branches:
      - main  # Replace with your desired branch name
jobs:
  invoke_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: test
        run: |
          env
          echo "**********************************"
          echo "${{ vars.TEN }}" > a.txt
          cat a.txt
